excerpt_separator: ""
highlighter: rouge
# Site settings
title:       Cierpienia M&#322;odego Kodera
email:       me@donpiekarz.pl
author:      DonPiekarz
description: "tylko sny odró&#380;niaj&#261; nas od maszyn"
baseurl:     ""
url:         "http://donpiekarz.pl"
date_format: "%Y-%m-%d"

# Google services
google_analytics: UA-73550761-1
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: donpiekarz

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
show_email: False
github_username: donpiekarz
bitbucket_username:
stackoverflow_id:
twitter_username: donpiekarz
facebook_username: pepiniera.net
skype_username:
steam_nickname:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Nowsze'
    older: 'Starsze'
  share_buttons:
    text:         'Udostępnij post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Zaktualizowano'
    minute_read:    'min czytania'
    related_posts:  'Powiazane posty'
  index:
    coming_soon: 'Wkrótce...'
  contact:
    email:    'Email adres'
    content:  'Co tam?'
    subject:  'Nowa poczta z bloga!'
    submit:   'Wyślij'
    ajax:
      sending:  'Wysyłam..'
      sent:     'Wysłano!'
      error:    'Błąd!'
  thanks: 'Dzięki za kontakt, odpowiem najszybciej jak to możliwe'


# Build settings
markdown: kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]
