excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://donpiekarz.github.io
title: Cierpienia m&#322;odego kodera
email: aaa@bbb.com
author: DonPiekarz
description: tylko sny odró&#380;niaj&#261; nas od maszyn
paginate: 10
